# Generated by Django 2.0 on 2019-12-11 10:10

import django.core.validators
from django.db import migrations, models
import package_directory.models


class Migration(migrations.Migration):

    dependencies = [
        ('package_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['package_name'], 'verbose_name': 'Application Android'},
        ),
        migrations.AlterField(
            model_name='application',
            name='apk_file',
            field=models.FileField(upload_to=package_directory.models.app_directory_path, validators=[django.core.validators.FileExtensionValidator(['apk'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
